apiVersion: v1
kind: Service
metadata:
  name: phobos-webapi
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'
  labels:
    app: domain-customers
spec:
  type: LoadBalancer
  ports:
    - name: query-http
      port: 1880
      protocol: TCP
      targetPort: 80
  selector:
    app: phobos-web
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: phobos-web
  labels:
    app: phobos-web
spec:
  serviceName: "phobos-web"
  replicas: 1
  selector:
    matchLabels:
      app: phobos-web
  template:
    metadata:
      labels:
        app: phobos-web
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: phobos-web
        image: petabridge.phobos.web.datadog:0.1.0
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: pb-configs
              key: environment
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog-secrets
              key: DD_API_KEY
        livenessProbe:
          tcpSocket:
            port: 4055
        readinessProbe:
          httpGet:
            path: "/"
            port: 80
        ports:
        - containerPort: 80
          protocol: TCP